services:
  mysql-db:
    image: mysql:8.0
    container_name: helpdesk-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: helpdesk_db
      MYSQL_USER: helpdesk_user
      MYSQL_PASSWORD: helpdesk_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  helpdesk-app:
    build: .
    container_name: helpdesk-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/helpdesk_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root_password
      - JWT_SECRET=a2ad753d3a3e819504079d82f15b39c7b2b9d940438cd4d654ab19e57515f06f
    restart: no

volumes:
  mysql_data: