spring:
  application:
    name: system-ticket-service-backend

  datasource:
    url: jdbc:mysql://localhost:3306/helpdesk_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: helpdesk_user
    password: helpdesk_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect